package output

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"
	"unicode"

	"github.com/supermodeltools/uncompact/internal/api"
)

// Renderer produces token-bounded Markdown context bombs.
type Renderer struct {
	maxTokens int
}

// NewRenderer creates a Renderer with the given token budget.
func NewRenderer(maxTokens int) *Renderer {
	return &Renderer{maxTokens: maxTokens}
}

// Section represents a block in the context bomb.
type Section struct {
	Title    string
	Content  string
	Required bool
}

// Render produces a Markdown context bomb from graph data.
// Returns (markdown, tokenCount, error).
func (r *Renderer) Render(g *api.GraphOutput) (string, int, error) {
	sections := r.buildSections(g)
	return r.assemble(sections, g)
}

func (r *Renderer) buildSections(g *api.GraphOutput) []Section {
	var sections []Section

	// Always include required sections first
	if g.Overview != "" {
		sections = append(sections, Section{
			Title:    "Project Overview",
			Content:  g.Overview,
			Required: true,
		})
	}

	// Pull typed nodes into sections
	nodesByType := make(map[string][]api.GraphNode)
	for _, n := range g.Nodes {
		nodesByType[n.Type] = append(nodesByType[n.Type], n)
	}

	if nodes, ok := nodesByType["recent_change"]; ok {
		sections = append(sections, Section{
			Title:    "Recent Changes",
			Content:  formatNodes(nodes),
			Required: true,
		})
	}

	if nodes, ok := nodesByType["task"]; ok {
		sections = append(sections, Section{
			Title:    "Active Tasks",
			Content:  formatNodes(nodes),
			Required: true,
		})
	}

	if nodes, ok := nodesByType["structure"]; ok {
		sections = append(sections, Section{
			Title:    "Project Structure",
			Content:  formatNodes(nodes),
			Required: false,
		})
	}

	if nodes, ok := nodesByType["dependency"]; ok {
		sections = append(sections, Section{
			Title:    "Dependencies",
			Content:  formatNodes(nodes),
			Required: false,
		})
	}

	if nodes, ok := nodesByType["custom"]; ok {
		sections = append(sections, Section{
			Title:    "Custom Context",
			Content:  formatNodes(nodes),
			Required: false,
		})
	}

	// Catch-all for unknown node types
	var otherNodes []api.GraphNode
	for t, nodes := range nodesByType {
		switch t {
		case "recent_change", "task", "structure", "dependency", "custom":
			continue
		default:
			otherNodes = append(otherNodes, nodes...)
		}
	}
	if len(otherNodes) > 0 {
		sections = append(sections, Section{
			Title:    "Additional Context",
			Content:  formatNodes(otherNodes),
			Required: false,
		})
	}

	return sections
}

func (r *Renderer) assemble(sections []Section, g *api.GraphOutput) (string, int, error) {
	stale := g.IsExpired()
	stalePfx := ""
	if stale {
		age := time.Since(g.FetchedAt).Round(time.Minute)
		stalePfx = fmt.Sprintf("> **[STALE: last updated %v ago]**\n\n", age)
	}

	var buf bytes.Buffer
	tmpl, err := template.New("header").Parse(headerTmpl)
	if err != nil {
		return "", 0, err
	}

	type headerData struct {
		Timestamp   string
		WorkspaceID string
	}
	if err := tmpl.Execute(&buf, headerData{
		Timestamp:   g.FetchedAt.Format(time.RFC3339),
		WorkspaceID: g.WorkspaceID,
	}); err != nil {
		return "", 0, err
	}

	header := stalePfx + buf.String()
	headerTokens := estimateTokens(header)
	budget := r.maxTokens - headerTokens - 20 // reserve 20 for footer

	if budget < 100 {
		return header, headerTokens, nil
	}

	var bodyParts []string

	// Required sections get budget priority
	var required, optional []Section
	for _, s := range sections {
		if s.Required {
			required = append(required, s)
		} else {
			optional = append(optional, s)
		}
	}

	remaining := budget
	for _, s := range required {
		rendered := renderSection(s)
		t := estimateTokens(rendered)
		if t > remaining {
			rendered = truncateSection(s, remaining)
			t = estimateTokens(rendered)
		}
		bodyParts = append(bodyParts, rendered)
		remaining -= t
	}

	for _, s := range optional {
		if remaining < 50 {
			break
		}
		rendered := renderSection(s)
		t := estimateTokens(rendered)
		if t > remaining {
			if remaining > 100 {
				rendered = truncateSection(s, remaining)
				t = estimateTokens(rendered)
			} else {
				break
			}
		}
		bodyParts = append(bodyParts, rendered)
		remaining -= t
	}

	body := strings.Join(bodyParts, "\n")
	footer := fmt.Sprintf("\n---\n*Context bomb generated by [Uncompact](https://github.com/supermodeltools/Uncompact). Token budget: %d/%d used.*\n",
		r.maxTokens-remaining, r.maxTokens)

	full := header + body + footer
	return full, estimateTokens(full), nil
}

// FallbackBomb emits a minimal static context bomb when the API is unavailable.
func FallbackBomb(workspaceName string, maxTokens int) string {
	return fmt.Sprintf(`<!-- UNCOMPACT FALLBACK -->
> **Note:** Supermodel API unavailable. Minimal fallback context below.

## Workspace
Current workspace: **%s**

*Run \`uncompact auth login\` if not authenticated. Run \`uncompact cache clear\` if cache is stale.*
`, workspaceName)
}

func renderSection(s Section) string {
	return fmt.Sprintf("### %s\n\n%s\n", s.Title, s.Content)
}

func truncateSection(s Section, tokenBudget int) string {
	// Roughly 4 chars per token
	charBudget := tokenBudget*4 - len(s.Title) - 10
	if charBudget < 20 {
		return fmt.Sprintf("### %s\n\n*[truncated]*\n", s.Title)
	}
	content := s.Content
	if len(content) > charBudget {
		content = content[:charBudget] + "…"
	}
	return fmt.Sprintf("### %s\n\n%s\n", s.Title, content)
}

func formatNodes(nodes []api.GraphNode) string {
	var sb strings.Builder
	for _, n := range nodes {
		if n.Label != "" {
			sb.WriteString("**")
			sb.WriteString(n.Label)
			sb.WriteString("**")
			if n.Content != "" {
				sb.WriteString(": ")
				sb.WriteString(n.Content)
			}
			sb.WriteString("\n\n")
		} else if n.Content != "" {
			sb.WriteString(n.Content)
			sb.WriteString("\n\n")
		}
	}
	return strings.TrimRight(sb.String(), "\n")
}

// estimateTokens approximates token count (roughly 1 token per 4 chars).
func estimateTokens(s string) int {
	words := 0
	inWord := false
	for _, r := range s {
		if unicode.IsSpace(r) {
			inWord = false
		} else if !inWord {
			words++
			inWord = true
		}
	}
	// Words * 1.3 is a reasonable approximation
	return int(float64(words)*1.3) + 1
}

const headerTmpl = `<!-- UNCOMPACT CONTEXT BOMB | generated: {{.Timestamp}}{{if .WorkspaceID}} | workspace: {{.WorkspaceID}}{{end}} -->

`
