package render

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"
	"unicode"

	"github.com/supermodeltools/uncompact/internal/api"
)

const contextBombTmpl = `# Uncompact Context — {{.ProjectName}}

> Injected by Uncompact at {{.Timestamp}}{{if .Stale}} | ⚠️ STALE: last updated {{.StaleDuration}}{{end}}

## Project Overview

**Name:** {{.Graph.Name}}
**Language:** {{.Graph.Language}}{{if .Graph.Framework}}
**Framework:** {{.Graph.Framework}}{{end}}{{if .Graph.Description}}
**Description:** {{.Graph.Description}}{{end}}
**Codebase:** {{.Graph.Stats.TotalFiles}} files · {{.Graph.Stats.TotalFunctions}} functions · {{.Graph.Stats.TotalLines}} lines
{{- if .Graph.Stats.Languages}}

**Languages:** {{languageList .Graph.Stats.Languages}}{{end}}

## Domain Map
{{range .Graph.Domains}}
### {{.Name}}
{{.Description}}
{{if .KeyFiles}}**Key files:** {{join .KeyFiles ", "}}
{{end}}{{if .Responsibilities}}**Responsibilities:**
{{range .Responsibilities}}- {{.}}
{{end}}{{end}}{{if .Subdomains}}**Subdomains:** {{join .Subdomains ", "}}
{{end}}{{if .DependsOn}}**Depends on:** {{join .DependsOn ", "}}
{{end}}{{end}}
---
*Generated by [Uncompact](https://github.com/supermodeltools/Uncompact)*`

// RenderOptions controls the context bomb output.
type RenderOptions struct {
	MaxTokens int
	Stale     bool
	StaleAt   *time.Time
}

// Render produces the context bomb Markdown, respecting the token budget.
func Render(graph *api.ProjectGraph, projectName string, opts RenderOptions) (string, int, error) {
	if opts.MaxTokens <= 0 {
		opts.MaxTokens = 2000
	}

	now := time.Now()

	data := struct {
		ProjectName   string
		Timestamp     string
		Graph         *api.ProjectGraph
		Stale         bool
		StaleDuration string
	}{
		ProjectName: projectName,
		Timestamp:   now.Format("2006-01-02 15:04:05 UTC"),
		Graph:       graph,
		Stale:       opts.Stale,
	}

	if opts.Stale && opts.StaleAt != nil {
		data.StaleDuration = humanDuration(now.Sub(*opts.StaleAt))
	}

	funcMap := template.FuncMap{
		"join": strings.Join,
		"languageList": func(langs map[string]int) string {
			parts := make([]string, 0, len(langs))
			for lang, count := range langs {
				parts = append(parts, fmt.Sprintf("%s (%d)", lang, count))
			}
			return strings.Join(parts, ", ")
		},
	}

	tmpl, err := template.New("context_bomb").Funcs(funcMap).Parse(contextBombTmpl)
	if err != nil {
		return "", 0, fmt.Errorf("parsing template: %w", err)
	}

	// First render the full output
	var full bytes.Buffer
	if err := tmpl.Execute(&full, data); err != nil {
		return "", 0, fmt.Errorf("rendering template: %w", err)
	}

	fullText := full.String()
	tokens := countTokens(fullText)

	if tokens <= opts.MaxTokens {
		return fullText, tokens, nil
	}

	// If over budget, truncate domains to fit
	return truncateToTokenBudget(graph, projectName, opts.MaxTokens)
}

// truncateToTokenBudget progressively drops lower-priority content to fit the token budget.
func truncateToTokenBudget(
	graph *api.ProjectGraph,
	projectName string,
	maxTokens int,
) (string, int, error) {

	// Build a minimal required header
	required := fmt.Sprintf(`# Uncompact Context — %s

**Language:** %s · **Files:** %d · **Functions:** %d`,
		projectName, graph.Language, graph.Stats.TotalFiles, graph.Stats.TotalFunctions,
	)

	reqTokens := countTokens(required)
	remaining := maxTokens - reqTokens

	var domainSections []string
	for _, d := range graph.Domains {
		section := buildDomainSection(d)
		sectionTokens := countTokens(section)
		if sectionTokens <= remaining {
			domainSections = append(domainSections, section)
			remaining -= sectionTokens
		}
		if remaining < 50 {
			break
		}
	}

	var sb strings.Builder
	sb.WriteString(required)
	if len(domainSections) > 0 {
		sb.WriteString("\n\n## Domain Map\n")
		for _, s := range domainSections {
			sb.WriteString(s)
		}
	}
	sb.WriteString("\n\n---\n*Generated by Uncompact (budget-truncated)*")

	result := sb.String()
	return result, countTokens(result), nil
}

func buildDomainSection(d api.Domain) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n### %s\n%s\n", d.Name, d.Description))
	if len(d.KeyFiles) > 0 {
		sb.WriteString(fmt.Sprintf("**Key files:** %s\n", strings.Join(d.KeyFiles, ", ")))
	}
	return sb.String()
}

// countTokens is a fast approximation: ~4 chars per token (GPT-style).
func countTokens(text string) int {
	words := 0
	inWord := false
	for _, r := range text {
		if unicode.IsSpace(r) {
			inWord = false
		} else if !inWord {
			words++
			inWord = true
		}
	}
	// Approximate: 1 token ≈ 0.75 words, or len/4 chars
	charEstimate := len(text) / 4
	wordEstimate := words * 100 / 75
	if charEstimate > wordEstimate {
		return charEstimate
	}
	return wordEstimate
}

// humanDuration returns a human-friendly duration string.
func humanDuration(d time.Duration) string {
	if d < time.Minute {
		return fmt.Sprintf("%d seconds", int(d.Seconds()))
	}
	if d < time.Hour {
		return fmt.Sprintf("%d minutes", int(d.Minutes()))
	}
	if d < 24*time.Hour {
		return fmt.Sprintf("%.1f hours", d.Hours())
	}
	return fmt.Sprintf("%.1f days", d.Hours()/24)
}
