package template

import (
	"bytes"
	"fmt"
	"strings"
	gotmpl "text/template"
	"time"
	"unicode"

	"github.com/supermodeltools/uncompact/internal/api"
	"github.com/supermodeltools/uncompact/internal/config"
	"github.com/supermodeltools/uncompact/internal/project"
	"github.com/supermodeltools/uncompact/internal/snapshot"
)

var rendererTmpl = gotmpl.Must(
	gotmpl.New("context_bomb").Funcs(gotmpl.FuncMap{
		"join":         strings.Join,
		"languageList": func(langs []string) string { return strings.Join(langs, ", ") },
		"add1":         func(i int) int { return i + 1 },
		"blockquote":   func(s string) string { return strings.ReplaceAll(s, "\n", "\n> ") },
	}).Parse(contextBombTmpl),
)

const contextBombTmpl = `# Uncompact Context — {{.ProjectName}}
{{- if .SessionSnapshot}}
{{.SessionSnapshot.Content}}
{{- end}}

> Injected by Uncompact at {{.Timestamp}}{{if .LocalMode}} | local mode (set SUPERMODEL_API_KEY for AI-powered features){{end}}{{if .Stale}} | ⚠️ STALE: last updated {{.StaleDuration}}{{end}}
{{- if .Graph.Stats.CircularDependencyCycles}}
> ⚠️ {{.Graph.Stats.CircularDependencyCycles}} circular dependency {{if eq .Graph.Stats.CircularDependencyCycles 1}}cycle{{else}}cycles{{end}} detected{{range .Graph.Cycles}}
> - {{join .Cycle " → "}}{{end}}
{{- end}}
{{- if and (not .LocalMode) (not .Graph.CircularDepsAnalyzed)}}
> ⚠️ Circular dependency analysis unavailable
{{- end}}

## Project Overview

**Name:** {{.Graph.Name}}
**Language:** {{.Graph.Language}}{{if .Graph.Framework}}
**Framework:** {{.Graph.Framework}}{{end}}{{if .Graph.Description}}
**Description:** {{.Graph.Description}}{{end}}
**Codebase:** {{.Graph.Stats.TotalFiles}} files · {{.Graph.Stats.TotalFunctions}} functions
{{- if .Graph.Stats.Languages}}

**Languages:** {{languageList .Graph.Stats.Languages}}{{end}}{{if .Graph.ExternalDeps}}
**Tech stack:** {{join .Graph.ExternalDeps ", "}}{{end}}
{{if .Graph.CriticalFiles}}
## Critical Files
{{range $i, $f := .Graph.CriticalFiles}}{{add1 $i}}. {{$f.Path}}{{if $f.RelationshipCount}} — {{$f.RelationshipCount}} relationships{{end}}
{{end}}{{end}}
## Domain Map
{{range .Graph.Domains}}
### {{.Name}}
{{.Description}}
{{if .KeyFiles}}**Key files:** {{join .KeyFiles ", "}}
{{end}}{{if .Responsibilities}}**Responsibilities:**
{{range .Responsibilities}}- {{.}}
{{end}}{{end}}{{if .Subdomains}}**Subdomains:**
{{range .Subdomains}}- {{.Name}}{{if .Description}}: {{.Description}}{{end}}
{{end}}{{end}}{{if .DependsOn}}**Depends on:** {{join .DependsOn ", "}}
{{end}}{{end}}{{- if .ClaudeMD}}
## Project Instructions (CLAUDE.md)

{{.ClaudeMD}}
{{- end}}{{if .WorkingMemory}}
## Working Memory

**Branch:** {{.WorkingMemory.Branch}}
{{- if .WorkingMemory.IssueNumber}}
**Issue #{{.WorkingMemory.IssueNumber}}:** {{.WorkingMemory.IssueTitle}}{{if .WorkingMemory.IssueBody}}
> {{.WorkingMemory.IssueBody | blockquote}}{{end}}
{{- end}}{{- if .WorkingMemory.ChangedFiles}}
**Changes on branch (vs {{.WorkingMemory.DefaultBranch}}):**
{{range .WorkingMemory.ChangedFiles}}  {{.}}
{{end}}{{- end}}{{- if .WorkingMemory.BranchCommits}}
**Recent commits:**
{{range .WorkingMemory.BranchCommits}}  {{.}}
{{end}}{{- end}}{{- if .WorkingMemory.Uncommitted}}
**Uncommitted:**
{{range .WorkingMemory.Uncommitted}}  {{.}}
{{end}}{{- end}}{{- end}}
---
*Generated by [Uncompact](https://github.com/supermodeltools/Uncompact)*`

// RenderOptions controls the context bomb output.
type RenderOptions struct {
	MaxTokens       int
	Stale           bool
	StaleAt         *time.Time // time the data was originally fetched (for "last updated X ago" banner)
	WorkingMemory   *project.WorkingMemory
	PostCompact     bool // append acknowledgment instruction for post-compact injection
	SessionSnapshot *snapshot.SessionSnapshot
	ClaudeMD        string // raw CLAUDE.md content (local mode)
	LocalMode       bool   // whether running in local mode (shows informational banner)
}

// Render produces the context bomb Markdown, respecting the token budget.
func Render(graph *api.ProjectGraph, projectName string, opts RenderOptions) (string, int, error) {
	if opts.MaxTokens <= 0 {
		opts.MaxTokens = config.DefaultMaxTokens
	}

	now := time.Now().UTC()

	staleDuration := ""
	if opts.Stale && opts.StaleAt != nil {
		staleDuration = humanDuration(now.Sub(*opts.StaleAt))
	}

	data := struct {
		ProjectName     string
		Timestamp       string
		Graph           *api.ProjectGraph
		Stale           bool
		StaleDuration   string
		WorkingMemory   *project.WorkingMemory
		SessionSnapshot *snapshot.SessionSnapshot
		ClaudeMD        string
		LocalMode       bool
	}{
		ProjectName:     projectName,
		Timestamp:       now.Format("2006-01-02 15:04:05 UTC"),
		Graph:           graph,
		Stale:           opts.Stale,
		StaleDuration:   staleDuration,
		WorkingMemory:   opts.WorkingMemory,
		SessionSnapshot: opts.SessionSnapshot,
		ClaudeMD:        opts.ClaudeMD,
		LocalMode:       opts.LocalMode,
	}

	// First render the full output
	var full bytes.Buffer
	if err := rendererTmpl.Execute(&full, data); err != nil {
		return "", 0, fmt.Errorf("rendering template: %w", err)
	}

	fullText := full.String()
	tokens := CountTokens(fullText)

	var result string
	var resultTokens int

	if tokens <= opts.MaxTokens {
		result, resultTokens = fullText, tokens
	} else {
		// If over budget, truncate domains to fit
		var err error
		result, resultTokens, err = truncateToTokenBudget(graph, projectName, opts.MaxTokens, graph.Stats.CircularDependencyCycles, opts.WorkingMemory, opts.SessionSnapshot, opts.ClaudeMD, opts.LocalMode, opts.Stale, staleDuration)
		if err != nil {
			return "", 0, err
		}
	}

	if opts.PostCompact {
		buildNote := func(n int) string {
			return fmt.Sprintf("\n\n> [uncompact] Context restored after compact (~%d tokens). Please acknowledge at the start of your response with exactly: \"✓ Uncompact: context restored (~%d tokens)\"", n, n)
		}
		note := buildNote(resultTokens)
		noteTokens := CountTokens(note)
		if opts.MaxTokens > 0 && resultTokens+noteTokens > opts.MaxTokens {
			budget := opts.MaxTokens - noteTokens
			if budget < 1 {
				budget = 1
			}
			if tokens <= budget {
				result, resultTokens = fullText, tokens
			} else {
				truncated, truncatedTokens, truncErr := truncateToTokenBudget(graph, projectName, budget, graph.Stats.CircularDependencyCycles, opts.WorkingMemory, opts.SessionSnapshot, opts.ClaudeMD, opts.LocalMode, opts.Stale, staleDuration)
				if truncErr != nil {
					return "", 0, truncErr
				}
				result, resultTokens = truncated, truncatedTokens
			}
			note = buildNote(resultTokens)
		}
		result += note
		resultTokens = CountTokens(result)
	}

	return result, resultTokens, nil
}

// truncateToTokenBudget progressively drops lower-priority content to fit the token budget.
func truncateToTokenBudget(
	graph *api.ProjectGraph,
	projectName string,
	maxTokens int,
	circularCycles int,
	wm *project.WorkingMemory,
	snap *snapshot.SessionSnapshot,
	claudeMD string,
	localMode bool,
	stale bool,
	staleDuration string,
) (string, int, error) {

	// Build a minimal required header
	var hdr strings.Builder
	hdr.WriteString(fmt.Sprintf("# Uncompact Context — %s\n\n", projectName))
	// Emit timestamp + stale banner (mirrors the main template banner)
	now := time.Now().UTC()
	banner := fmt.Sprintf("> Injected by Uncompact at %s", now.Format("2006-01-02 15:04:05 UTC"))
	if localMode {
		banner += " | local mode (set SUPERMODEL_API_KEY for AI-powered features)"
	}
	if stale && staleDuration != "" {
		banner += fmt.Sprintf(" | ⚠️ STALE: last updated %s", staleDuration)
	}
	hdr.WriteString(banner + "\n")
	if circularCycles > 0 {
		label := "cycles"
		if circularCycles == 1 {
			label = "cycle"
		}
		hdr.WriteString(fmt.Sprintf("> ⚠️ %d circular dependency %s detected\n", circularCycles, label))
		for _, c := range graph.Cycles {
			hdr.WriteString(fmt.Sprintf("> - %s\n", strings.Join(c.Cycle, " → ")))
		}
		hdr.WriteString("\n")
	} else if !localMode && !graph.CircularDepsAnalyzed {
		hdr.WriteString("> ⚠️ Circular dependency analysis unavailable\n\n")
	}
	hdr.WriteString(fmt.Sprintf(
		"**Language:** %s · **Files:** %d · **Functions:** %d",
		graph.Language, graph.Stats.TotalFiles, graph.Stats.TotalFunctions,
	))
	required := hdr.String()

	reqTokens := CountTokens(required)
	if reqTokens > maxTokens {
		fallback := "# Uncompact Context\n\n(Budget too small; increase --max-tokens)"
		return fallback, CountTokens(fallback), nil
	}
	remaining := maxTokens - reqTokens

	var sb strings.Builder
	sb.WriteString(required)

	// Session snapshot — high-priority: include before project structure if present
	if snap != nil && snap.Content != "" {
		section := "\n\n" + snap.Content
		sectionTokens := CountTokens(section)
		if sectionTokens <= remaining {
			sb.WriteString(section)
			remaining -= sectionTokens
		}
	}

	// Include critical files section before domain map — it's high-priority read order context.
	if len(graph.CriticalFiles) > 0 {
		header := "\n\n## Critical Files\n"
		headerTokens := CountTokens(header)
		if headerTokens <= remaining {
			sb.WriteString(header)
			remaining -= headerTokens
			for i, f := range graph.CriticalFiles {
				var line string
				if f.RelationshipCount > 0 {
					line = fmt.Sprintf("%d. %s — %d relationships\n", i+1, f.Path, f.RelationshipCount)
				} else {
					line = fmt.Sprintf("%d. %s\n", i+1, f.Path)
				}
				lineTokens := CountTokens(line)
				if lineTokens > remaining {
					break
				}
				sb.WriteString(line)
				remaining -= lineTokens
			}
		}
	}

	header := "\n\n## Domain Map\n"
	headerTokens := CountTokens(header)
	if headerTokens <= remaining {
		sectionBudget := remaining - headerTokens
		var domainSections []string
		for _, d := range graph.Domains {
			section := buildDomainSection(d)
			sectionTokens := CountTokens(section)
			if sectionTokens <= sectionBudget {
				domainSections = append(domainSections, section)
				sectionBudget -= sectionTokens
			}
			if sectionBudget < 50 {
				break
			}
		}
		if len(domainSections) > 0 {
			sb.WriteString(header)
			remaining = sectionBudget
			for _, s := range domainSections {
				sb.WriteString(s)
			}
		}
	}

	// CLAUDE.md — include if it fits within remaining budget
	if claudeMD != "" {
		header := "\n\n## Project Instructions (CLAUDE.md)\n\n"
		headerTokens := CountTokens(header)
		contentTokens := CountTokens(claudeMD)
		if headerTokens+contentTokens <= remaining {
			sb.WriteString(header)
			sb.WriteString(claudeMD)
			sb.WriteString("\n")
			remaining -= headerTokens + contentTokens + 1
		}
	}

	// Working memory — append with remaining budget, dropping content by priority
	if wm != nil {
		wmSection := buildWorkingMemorySection(wm, remaining)
		if wmSection != "" {
			sb.WriteString(wmSection)
			remaining -= CountTokens(wmSection)
		}
	}

	footer := "\n\n---\n*Generated by Uncompact (budget-truncated)*"
	if CountTokens(footer) <= remaining {
		sb.WriteString(footer)
	}

	result := sb.String()
	return result, CountTokens(result), nil
}

func buildDomainSection(d api.Domain) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n### %s\n%s\n", d.Name, d.Description))
	if len(d.KeyFiles) > 0 {
		sb.WriteString(fmt.Sprintf("**Key files:** %s\n", strings.Join(d.KeyFiles, ", ")))
	}
	if len(d.Subdomains) > 0 {
		sb.WriteString("**Subdomains:**\n")
		for _, s := range d.Subdomains {
			if s.Description != "" {
				sb.WriteString(fmt.Sprintf("- %s: %s\n", s.Name, s.Description))
			} else {
				sb.WriteString(fmt.Sprintf("- %s\n", s.Name))
			}
		}
	}
	return sb.String()
}

// buildWorkingMemorySection renders the Working Memory section within the given token budget.
// Content is dropped in priority order: issue body first, then commits, keeping changed files.
func buildWorkingMemorySection(wm *project.WorkingMemory, budget int) string {
	var header strings.Builder
	header.WriteString("\n\n## Working Memory\n\n")
	header.WriteString(fmt.Sprintf("**Branch:** %s\n", wm.Branch))
	if wm.IssueNumber > 0 && wm.IssueTitle != "" {
		header.WriteString(fmt.Sprintf("**Issue #%d:** %s\n", wm.IssueNumber, wm.IssueTitle))
	}
	headerStr := header.String()

	var changedSection string
	if len(wm.ChangedFiles) > 0 {
		defaultBranch := wm.DefaultBranch
		if defaultBranch == "" {
			defaultBranch = "main"
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("\n**Changes on branch (vs %s):**\n", defaultBranch))
		for _, f := range wm.ChangedFiles {
			sb.WriteString(fmt.Sprintf("  %s\n", f))
		}
		changedSection = sb.String()
	}

	var commitsSection string
	if len(wm.BranchCommits) > 0 {
		var sb strings.Builder
		sb.WriteString("\n**Recent commits:**\n")
		for _, c := range wm.BranchCommits {
			sb.WriteString(fmt.Sprintf("  %s\n", c))
		}
		commitsSection = sb.String()
	}

	var issueBodySection string
	if wm.IssueBody != "" {
		issueBodySection = fmt.Sprintf("> %s\n", strings.ReplaceAll(wm.IssueBody, "\n", "\n> "))
	}

	var uncommittedSection string
	if len(wm.Uncommitted) > 0 {
		var sb strings.Builder
		sb.WriteString("\n**Uncommitted:**\n")
		for _, u := range wm.Uncommitted {
			sb.WriteString(fmt.Sprintf("  %s\n", u))
		}
		uncommittedSection = sb.String()
	}

	// Try progressively smaller content, dropping lowest-priority first.
	candidates := []string{
		headerStr + issueBodySection + changedSection + commitsSection + uncommittedSection,
		headerStr + changedSection + commitsSection + uncommittedSection,
		headerStr + changedSection + uncommittedSection,
		headerStr + changedSection,
		headerStr,
	}
	for _, candidate := range candidates {
		if CountTokens(candidate) <= budget {
			return candidate
		}
	}
	return ""
}

// CountTokens is a fast approximation: ~4 chars per token (GPT-style).
// It uses max(charEstimate, wordEstimate) to better handle typical prose/code.
func CountTokens(text string) int {
	words := 0
	inWord := false
	for _, r := range text {
		if unicode.IsSpace(r) {
			inWord = false
		} else if !inWord {
			words++
			inWord = true
		}
	}
	// Approximate: 1 token ≈ 0.75 words, or len/4 bytes
	charEstimate := len(text) / 4
	wordEstimate := words * 100 / 75
	if charEstimate > wordEstimate {
		return charEstimate
	}
	return wordEstimate
}

// humanDuration returns a human-friendly duration string.
func humanDuration(d time.Duration) string {
	if d < time.Minute {
		return fmt.Sprintf("%d seconds", int(d.Seconds()))
	}
	if d < time.Hour {
		return fmt.Sprintf("%d minutes", int(d.Minutes()))
	}
	if d < 24*time.Hour {
		return fmt.Sprintf("%.1f hours", d.Hours())
	}
	return fmt.Sprintf("%.1f days", d.Hours()/24)
}
